### ISSUE TITLE
failed to upload spans to google trace

### ISSUE THREAD

**Issue by stephanos** [tsloughter/oc_google_reporter#7]
I'm seeing errors from Google Cloud in my logs.

It used to work just fine, but I haven't worked on the app in quite a while. I updated the dependencies recently, but after rolling that back I still see the errors.

This might totally be a user error, I haven't been able to investigate yet. Just thought I'd share it in case it's obvious or actually an issue.

Example log:
`failed to upload spans to google trace: %{"error" => %{"code" => 400, "details" => [%{"@type" => "type.googleapis.com/google.rpc.BadRequest", "fieldViolations" => [%{"description" => "Invalid JSON payload received. Unknown name \"endTime\" at 'traces.traces[0].spans[0]': Proto field is not repeating, cannot start list.", "field" => "traces.traces[0].spans[0]"}, %{"description" => "Invalid JSON payload received. Unknown name \"startTime\" at 'traces.traces[0].spans[0]': Proto field is not repeating, cannot start list.", "field" => "traces.traces[0].spans[0]"}]}], "message" => "Invalid JSON payload received. Unknown name \"endTime\" at 'traces.traces[0].spans[0]': Proto field is not repeating, cannot start list.\nInvalid JSON payload received. Unknown name \"startTime\" at 'traces.traces[0].spans[0]': Proto field is not repeating, cannot start list.", "status" => "INVALID_ARGUMENT"}}`

**Comment by stephanos** [comment]
This is my config:
```
config :opencensus,
  reporters: [{:oc_google_reporter,
    %{
      reporter: :oc_google_reporter_v2,
      project_id: "<MY ID>"
    }
  }]
```

And this is my plug:
```
defmodule Shared.Plug.Span do
  import Plug.Conn
  require Logger

  def init(default), do: default

  def call(conn, _default) do
    parent_span_ctx =
      Map.get_lazy(conn.private, :opencensus_span_ctx, fn ->
        :oc_propagation_http_tracecontext.from_headers(conn.req_headers)
      end)
    :ocp.with_span_ctx(parent_span_ctx)

    router = conn.private[:phoenix_router]
    %{
      plug: controller,
      plug_opts: action,
    } = Phoenix.Router.route_info(router, conn.method, conn.request_path, conn.host)
    :ocp.with_child_span("#{conn.method} #{conn.request_path}", %{
      "type" => "http",
      "http.host" => conn.host,
      "http.method" => conn.method,
      "http.path" => conn.request_path,
      "http.request_size" => conn |> get_req_header("content-length") |> List.first(),
      "http.user_agent" => conn |> get_req_header("user-agent") |> List.first(),
      "http.url" => request_url(conn),
      "phoenix.controller" => controller,
      "phoenix.action" => action
    })
    span_ctx = :ocp.current_span_ctx()

    register_before_send(conn, fn (conn) ->
      :oc_trace.finish_span(span_ctx)
      :ocp.with_span_ctx(parent_span_ctx)
      conn
    end)
  end
end
```

My mix.exs:
```
      {:opencensus, "~> 0.9.0", override: true},
      {:opencensus_telemetry, "~> 0.1.0"},
      {:opencensus_elixir, "~> 0.4.0"},
      {:oc_google_reporter, "~> 0.4.0"},
```

**Comment by tsloughter** [comment]
I haven't used that reporter in a long time but someone else is using it successfully recently I thought. They asked me to publish a new version. Unless that was you, hehe

Are you on Elixir slack in the opencensus channel?

**Comment by tsloughter** [comment]
Oh no, it was @fredr who asked on slack and I published the latest version. But you also seem to be using the latest.

**Comment by tsloughter** [comment]
@fredr are you using v1? Guessing v2 has some changes like changing `endTime` to another name.

**Comment by fredr** [comment]
We are using v2, haven't seen these errors 

The changed in the publish was for v2, that had already been fixed for v1 some versions prior

**Comment by fredr** [comment]
@stephanos is this still an issue for you, or did you solve it? As I said, we are running the v2 reporter as well, without any problems. But maybe we are doing something differently.

Maybe you could try to enable the debug-reporter and see if the data looks weird in any way (https://github.com/opencensus-beam/opencensus_elixir#troubleshooting)

**Comment by stephanos** [comment]
Thanks for the tip about the debugging, I'll try that!
I'll open an issue if I find something more concrete.

**Comment by stephanos** [comment]
Hm, I tried to print to stdout and I'm seeing this:

```
{span,<<"WebSocket.connect">>,230645895616194845522852166468472151322,
7325955264713890934,undefined,undefined,1,'SPAN_KIND_UNSPECIFIED',
{-576455691675621978,2166904053117851039},
{-576455691675414286,2166904053117851039},
#{},undefined,[],[],undefined,undefined,undefined}
```

Does that look right to you, I have no idea!

Well, then I just turned on the exporter during testing and added a debug statement and found this (snippet):
```
"spans\":[{\"endTime\":[50,48,50,48,45,48,53,45,50,53,84,49,54,58,50,57,58,53,50,46,50,51,51,56,54,48,45,48,55,58,48,48]
```
The end time is a character list instead of a string! Exactly what that error said.

I'm not sure how that happened, do you :-?

**Comment by tsloughter** [comment]
Hm, this reporter doesn't use websockets, that may be the issue.

**Comment by stephanos** [comment]
I don't think that's it. I had that problem without websockets as well. That's just the name of the module essentially.

**Comment by stephanos** [comment]
```
> [50,48,50,48,45,48,53,45,50,53,84,49,54,58,50,57,58,53,50,46,50,51,51,56,54,48,45,48,55,58,48,48] |> to_string()
> "2020-05-25T16:29:52.233860-07:00"
```

**Comment by stephanos** [comment]
I wonder if the `hackney` or Erlang version is relevant? I'm using `hackney` "1.15.2" and Erlang "22.3" and `wts` "0.4.0".

**Comment by stephanos** [comment]
That's it. I just downgraded `wts` to 0.3.0 and it works now.

That means these results look different in 0.4.0:
```
  startTime => wts:rfc3339(StartTime),
  endTime => wts:rfc3339(EndTime),
```

This seems to be the relevant change:
https://diff.hex.pm/diff/wts/0.3.0..0.4.0#104037148--75
